package com.solgases.unitofmeasure.controller;

import com.solgases.unitofmeasure.dto.UnitOfMeasureRequest;
import com.solgases.unitofmeasure.dto.UnitOfMeasureResponse;
import com.solgases.unitofmeasure.service.UnitOfMeasureService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import java.net.URI;
import java.util.List;
import org.springframework.http.ProblemDetail;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

@RestController
@RequestMapping("/api/units-of-measure")
@Tag(name = "Units of measure", description = "Management of the catalog of units of measure")
public class UnitOfMeasureController {

    private static final String PROBLEM_JSON = "application/problem+json";

    private final UnitOfMeasureService unitOfMeasureService;

    public UnitOfMeasureController(UnitOfMeasureService unitOfMeasureService) {
        this.unitOfMeasureService = unitOfMeasureService;
    }

    @PostMapping
    @Operation(summary = "Create a unit of measure",
            description = "Creates a new unit of measure. It is always created active. The id is generated by the server.")
    @ApiResponse(responseCode = "201", description = "Unit of measure created",
            content = @Content(schema = @Schema(implementation = UnitOfMeasureResponse.class)))
    @ApiResponse(responseCode = "400", description = "Invalid request body",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    @ApiResponse(responseCode = "409", description = "A unit of measure with the same code already exists",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    public ResponseEntity<UnitOfMeasureResponse> create(@Valid @RequestBody UnitOfMeasureRequest request) {
        UnitOfMeasureResponse created = unitOfMeasureService.create(request);
        URI location = ServletUriComponentsBuilder.fromCurrentRequest()
                .path("/{id}")
                .buildAndExpand(created.id())
                .toUri();
        return ResponseEntity.created(location).body(created);
    }

    @GetMapping
    @Operation(summary = "List units of measure",
            description = "Returns all units of measure, both active and inactive.")
    @ApiResponse(responseCode = "200", description = "List of units of measure",
            content = @Content(array = @ArraySchema(schema = @Schema(implementation = UnitOfMeasureResponse.class))))
    public List<UnitOfMeasureResponse> findAll() {
        return unitOfMeasureService.findAll();
    }

    @GetMapping("/{id}")
    @Operation(summary = "Get a unit of measure by id")
    @ApiResponse(responseCode = "200", description = "Unit of measure found",
            content = @Content(schema = @Schema(implementation = UnitOfMeasureResponse.class)))
    @ApiResponse(responseCode = "400", description = "The id is not a valid number",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    @ApiResponse(responseCode = "404", description = "Unit of measure not found",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    public UnitOfMeasureResponse findById(
            @Parameter(description = "Unit of measure identifier", example = "1") @PathVariable Long id) {
        return unitOfMeasureService.findById(id);
    }

    @PutMapping("/{id}")
    @Operation(summary = "Update a unit of measure",
            description = "Replaces the editable data (code and name). The active flag is not modified; "
                    + "use the activate and deactivate operations for that.")
    @ApiResponse(responseCode = "200", description = "Unit of measure updated",
            content = @Content(schema = @Schema(implementation = UnitOfMeasureResponse.class)))
    @ApiResponse(responseCode = "400", description = "Invalid id or request body",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    @ApiResponse(responseCode = "404", description = "Unit of measure not found",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    @ApiResponse(responseCode = "409", description = "Another unit of measure already uses the same code",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    public UnitOfMeasureResponse update(
            @Parameter(description = "Unit of measure identifier", example = "1") @PathVariable Long id,
            @Valid @RequestBody UnitOfMeasureRequest request) {
        return unitOfMeasureService.update(id, request);
    }

    @PatchMapping("/{id}/activate")
    @Operation(summary = "Activate a unit of measure",
            description = "Marks the unit of measure as active. Idempotent: if it is already active, the current state is returned.")
    @ApiResponse(responseCode = "200", description = "Unit of measure is active",
            content = @Content(schema = @Schema(implementation = UnitOfMeasureResponse.class)))
    @ApiResponse(responseCode = "400", description = "The id is not a valid number",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    @ApiResponse(responseCode = "404", description = "Unit of measure not found",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    public UnitOfMeasureResponse activate(
            @Parameter(description = "Unit of measure identifier", example = "1") @PathVariable Long id) {
        return unitOfMeasureService.activate(id);
    }

    @PatchMapping("/{id}/deactivate")
    @Operation(summary = "Deactivate a unit of measure",
            description = "Marks the unit of measure as inactive. Idempotent: if it is already inactive, the current state is returned. "
                    + "Units of measure are never deleted. Deactivating a unit does not affect products that already use it.")
    @ApiResponse(responseCode = "200", description = "Unit of measure is inactive",
            content = @Content(schema = @Schema(implementation = UnitOfMeasureResponse.class)))
    @ApiResponse(responseCode = "400", description = "The id is not a valid number",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    @ApiResponse(responseCode = "404", description = "Unit of measure not found",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    public UnitOfMeasureResponse deactivate(
            @Parameter(description = "Unit of measure identifier", example = "1") @PathVariable Long id) {
        return unitOfMeasureService.deactivate(id);
    }
}
