package com.solgases.infrastructure.api.rest;

import com.solgases.application.dto.CategoryResult;
import com.solgases.application.port.in.ActivateCategoryUseCase;
import com.solgases.application.port.in.CreateCategoryUseCase;
import com.solgases.application.port.in.DeactivateCategoryUseCase;
import com.solgases.application.port.in.GetCategoryByIdUseCase;
import com.solgases.application.port.in.ListCategoriesUseCase;
import com.solgases.application.port.in.UpdateCategoryUseCase;
import com.solgases.infrastructure.api.dto.CategoryRequest;
import com.solgases.infrastructure.api.dto.CategoryResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import java.net.URI;
import java.util.List;
import org.springframework.http.ProblemDetail;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

@RestController
@RequestMapping("/api/categories")
@Tag(name = "Categories", description = "Management of product categories")
public class CategoryController {

    private static final String PROBLEM_JSON = "application/problem+json";

    private final CreateCategoryUseCase createCategoryUseCase;
    private final ListCategoriesUseCase listCategoriesUseCase;
    private final GetCategoryByIdUseCase getCategoryByIdUseCase;
    private final UpdateCategoryUseCase updateCategoryUseCase;
    private final ActivateCategoryUseCase activateCategoryUseCase;
    private final DeactivateCategoryUseCase deactivateCategoryUseCase;

    public CategoryController(CreateCategoryUseCase createCategoryUseCase,
            ListCategoriesUseCase listCategoriesUseCase, GetCategoryByIdUseCase getCategoryByIdUseCase,
            UpdateCategoryUseCase updateCategoryUseCase, ActivateCategoryUseCase activateCategoryUseCase,
            DeactivateCategoryUseCase deactivateCategoryUseCase) {
        this.createCategoryUseCase = createCategoryUseCase;
        this.listCategoriesUseCase = listCategoriesUseCase;
        this.getCategoryByIdUseCase = getCategoryByIdUseCase;
        this.updateCategoryUseCase = updateCategoryUseCase;
        this.activateCategoryUseCase = activateCategoryUseCase;
        this.deactivateCategoryUseCase = deactivateCategoryUseCase;
    }

    @PostMapping
    @Operation(summary = "Create a category",
            description = "Creates a new category. It is always created active. The id is generated by the server.")
    @ApiResponse(responseCode = "201", description = "Category created",
            content = @Content(schema = @Schema(implementation = CategoryResponse.class)))
    @ApiResponse(responseCode = "400", description = "Invalid request body (blank name, name longer than 100 characters or malformed JSON)",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    @ApiResponse(responseCode = "409", description = "A category with the same name already exists",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    public ResponseEntity<CategoryResponse> create(@Valid @RequestBody CategoryRequest request) {
        CategoryResponse created = CategoryApiMapper.toResponse(
                createCategoryUseCase.execute(CategoryApiMapper.toCommand(request)));
        URI location = ServletUriComponentsBuilder.fromCurrentRequest()
                .path("/{id}")
                .buildAndExpand(created.id())
                .toUri();
        return ResponseEntity.created(location).body(created);
    }

    @GetMapping
    @Operation(summary = "List categories",
            description = "Returns all categories, both active and inactive. No filtering, sorting or pagination is applied.")
    @ApiResponse(responseCode = "200", description = "List of categories",
            content = @Content(array = @ArraySchema(schema = @Schema(implementation = CategoryResponse.class))))
    public List<CategoryResponse> findAll() {
        return listCategoriesUseCase.execute().stream().map(CategoryApiMapper::toResponse).toList();
    }

    @GetMapping("/{id}")
    @Operation(summary = "Get a category by id")
    @ApiResponse(responseCode = "200", description = "Category found",
            content = @Content(schema = @Schema(implementation = CategoryResponse.class)))
    @ApiResponse(responseCode = "400", description = "The id is not a valid number",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    @ApiResponse(responseCode = "404", description = "Category not found",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    public CategoryResponse findById(
            @Parameter(description = "Category identifier", example = "1") @PathVariable Long id) {
        var result = getCategoryByIdUseCase.execute(id);
        return CategoryApiMapper.toResponse(result);
    }

    @PutMapping("/{id}")
    @Operation(summary = "Update a category",
            description = "Replaces the editable data of the category (its name). The active flag is not modified; "
                    + "use the activate and deactivate operations for that.")
    @ApiResponse(responseCode = "200", description = "Category updated",
            content = @Content(schema = @Schema(implementation = CategoryResponse.class)))
    @ApiResponse(responseCode = "400", description = "Invalid id or request body",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    @ApiResponse(responseCode = "404", description = "Category not found",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    @ApiResponse(responseCode = "409", description = "Another category already uses the same name",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    public CategoryResponse update(
            @Parameter(description = "Category identifier", example = "1") @PathVariable Long id,
            @Valid @RequestBody CategoryRequest request) {
        return CategoryApiMapper.toResponse(updateCategoryUseCase.execute(id, CategoryApiMapper.toCommand(request)));
    }

    @PatchMapping("/{id}/activate")
    @Operation(summary = "Activate a category",
            description = "Marks the category as active. Idempotent: if it is already active, the current state is returned.")
    @ApiResponse(responseCode = "200", description = "Category is active",
            content = @Content(schema = @Schema(implementation = CategoryResponse.class)))
    @ApiResponse(responseCode = "400", description = "The id is not a valid number",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    @ApiResponse(responseCode = "404", description = "Category not found",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    public CategoryResponse activate(
            @Parameter(description = "Category identifier", example = "1") @PathVariable Long id) {
        return CategoryApiMapper.toResponse(activateCategoryUseCase.execute(id));
    }

    @PatchMapping("/{id}/deactivate")
    @Operation(summary = "Deactivate a category",
            description = "Marks the category as inactive. Idempotent: if it is already inactive, the current state is returned. "
                    + "Categories are never deleted.")
    @ApiResponse(responseCode = "200", description = "Category is inactive",
            content = @Content(schema = @Schema(implementation = CategoryResponse.class)))
    @ApiResponse(responseCode = "400", description = "The id is not a valid number",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    @ApiResponse(responseCode = "404", description = "Category not found",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    public CategoryResponse deactivate(
            @Parameter(description = "Category identifier", example = "1") @PathVariable Long id) {
        return CategoryApiMapper.toResponse(deactivateCategoryUseCase.execute(id));
    }
}
