package com.solgases.infrastructure.api.rest;

import com.solgases.application.port.in.ActivateUserUseCase;
import com.solgases.application.port.in.CreateUserUseCase;
import com.solgases.application.port.in.DeactivateUserUseCase;
import com.solgases.application.port.in.GetUserByIdUseCase;
import com.solgases.application.port.in.ListUsersUseCase;
import com.solgases.application.port.in.UpdateUserUseCase;
import com.solgases.infrastructure.api.dto.UserRequest;
import com.solgases.infrastructure.api.dto.UserResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import java.net.URI;
import java.util.List;
import org.springframework.http.ProblemDetail;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

@RestController
@RequestMapping("/api/users")
@Tag(name = "Users", description = "Administration of internal users and their roles. No authentication is "
        + "applied yet: intended for local development use only.")
public class UserController {

    private static final String PROBLEM_JSON = "application/problem+json";

    private final CreateUserUseCase createUserUseCase;
    private final ListUsersUseCase listUsersUseCase;
    private final GetUserByIdUseCase getUserByIdUseCase;
    private final UpdateUserUseCase updateUserUseCase;
    private final ActivateUserUseCase activateUserUseCase;
    private final DeactivateUserUseCase deactivateUserUseCase;

    public UserController(CreateUserUseCase createUserUseCase, ListUsersUseCase listUsersUseCase,
            GetUserByIdUseCase getUserByIdUseCase, UpdateUserUseCase updateUserUseCase,
            ActivateUserUseCase activateUserUseCase, DeactivateUserUseCase deactivateUserUseCase) {
        this.createUserUseCase = createUserUseCase;
        this.listUsersUseCase = listUsersUseCase;
        this.getUserByIdUseCase = getUserByIdUseCase;
        this.updateUserUseCase = updateUserUseCase;
        this.activateUserUseCase = activateUserUseCase;
        this.deactivateUserUseCase = deactivateUserUseCase;
    }

    @PostMapping
    @Operation(summary = "Create a user",
            description = "Creates a new user with the given roles. It is always created active. "
                    + "The id is generated by the server.")
    @ApiResponse(responseCode = "201", description = "User created",
            content = @Content(schema = @Schema(implementation = UserResponse.class)))
    @ApiResponse(responseCode = "400", description = "Invalid request body (blank or too long fields, missing "
            + "roleIds or malformed JSON)",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    @ApiResponse(responseCode = "404", description = "One or more roles do not exist",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    @ApiResponse(responseCode = "409", description = "A user with the same username already exists",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    public ResponseEntity<UserResponse> create(@Valid @RequestBody UserRequest request) {
        UserResponse created = UserApiMapper.toResponse(createUserUseCase.execute(UserApiMapper.toCommand(request)));
        URI location = ServletUriComponentsBuilder.fromCurrentRequest()
                .path("/{id}")
                .buildAndExpand(created.id())
                .toUri();
        return ResponseEntity.created(location).body(created);
    }

    @GetMapping
    @Operation(summary = "List users",
            description = "Returns all users, active and inactive, with their roles and permissions. "
                    + "No filtering, sorting or pagination is applied.")
    @ApiResponse(responseCode = "200", description = "List of users",
            content = @Content(array = @ArraySchema(schema = @Schema(implementation = UserResponse.class))))
    public List<UserResponse> findAll() {
        return listUsersUseCase.execute().stream().map(UserApiMapper::toResponse).toList();
    }

    @GetMapping("/{id}")
    @Operation(summary = "Get a user by id")
    @ApiResponse(responseCode = "200", description = "User found",
            content = @Content(schema = @Schema(implementation = UserResponse.class)))
    @ApiResponse(responseCode = "400", description = "The id is not a valid number",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    @ApiResponse(responseCode = "404", description = "User not found",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    public UserResponse findById(@Parameter(description = "User identifier", example = "1") @PathVariable Long id) {
        return UserApiMapper.toResponse(getUserByIdUseCase.execute(id));
    }

    @PutMapping("/{id}")
    @Operation(summary = "Update a user",
            description = "Replaces username, display name and roles. The active flag is not modified; "
                    + "use the activate and deactivate operations for that.")
    @ApiResponse(responseCode = "200", description = "User updated",
            content = @Content(schema = @Schema(implementation = UserResponse.class)))
    @ApiResponse(responseCode = "400", description = "Invalid id or request body",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    @ApiResponse(responseCode = "404", description = "User or one or more roles not found",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    @ApiResponse(responseCode = "409", description = "Another user already uses the same username",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    public UserResponse update(@Parameter(description = "User identifier", example = "1") @PathVariable Long id,
            @Valid @RequestBody UserRequest request) {
        return UserApiMapper.toResponse(updateUserUseCase.execute(id, UserApiMapper.toCommand(request)));
    }

    @PatchMapping("/{id}/activate")
    @Operation(summary = "Activate a user",
            description = "Marks the user as active. Idempotent: if it is already active, the current state is returned.")
    @ApiResponse(responseCode = "200", description = "User is active",
            content = @Content(schema = @Schema(implementation = UserResponse.class)))
    @ApiResponse(responseCode = "400", description = "The id is not a valid number",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    @ApiResponse(responseCode = "404", description = "User not found",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    public UserResponse activate(@Parameter(description = "User identifier", example = "1") @PathVariable Long id) {
        return UserApiMapper.toResponse(activateUserUseCase.execute(id));
    }

    @PatchMapping("/{id}/deactivate")
    @Operation(summary = "Deactivate a user",
            description = "Marks the user as inactive. Idempotent: if it is already inactive, the current state is "
                    + "returned. Users are never deleted.")
    @ApiResponse(responseCode = "200", description = "User is inactive",
            content = @Content(schema = @Schema(implementation = UserResponse.class)))
    @ApiResponse(responseCode = "400", description = "The id is not a valid number",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    @ApiResponse(responseCode = "404", description = "User not found",
            content = @Content(mediaType = PROBLEM_JSON, schema = @Schema(implementation = ProblemDetail.class)))
    public UserResponse deactivate(@Parameter(description = "User identifier", example = "1") @PathVariable Long id) {
        return UserApiMapper.toResponse(deactivateUserUseCase.execute(id));
    }
}
